spring:
  # mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: admin
  redis:
    database: 1
    host: localhost
    port: 6379
    password: redis123
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 5000ms
        min-idle: 0
        max-idle: 8