spring:
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.lwn.repo.entity
  configuration.map-underscore-to-camel-case: true
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  config: classpath:logback-spring.xml