server:
  servlet:
    context-path: /service-demo
  port: 8762

spring:
  profiles:
    active: dev
  application:
    name: service-demo
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.lwn.repo.entity
  configuration.map-underscore-to-camel-case: true
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

my:
  key-prefix: lwn_prefix
logging:
  config: classpath:logback-spring.xml